### ISSUE TITLE
Golang JWT Package use

### ISSUE THREAD

**Issue by iqbal167** [jabardigitalservice/event-management-system#2]
# Issues
- https://github.com/jabardigitalservice/event-management-system/security/dependabot/1

## Suggestion
- https://github.com/golang-jwt/jwt

**Comment by johndy2742** [comment]
there is two version option we can migrate to which one should we choose kang @iqbal167 version 4 or version 5?

**Comment by iqbal167** [comment]
use version 5 @johndy2742
